version: '3.9'
services:
  frontend:
    build: ./web
    ports:
      - 3000:3000
    working_dir: /app-frontend
    volumes:
      - ./web/src:/app-frontend/src
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - REACT_APP_BASE_URL=http://localhost:3030
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3000" ]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build: ./server
    ports:
      - 3030:3030
    working_dir: /app-backend
    volumes:
      - ./server/src:/app-backend/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3030
      - JWT_SECRET=jwt_secret
      - DATABASE_URL=postgres://postgres:postgres@db:5432/blog
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3030" ]
      timeout: 10s
      retries: 5
  db:
    image: postgres
    container_name: db
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: 'always'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_NICE
volumes:
  postgres-data: