
version: "3.9"

services:
  
  db:
    container_name: blog_db
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
 